development:
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
  GOOGLE_CLIENT_ID:  <%= ENV['GOOGLE_CLIENT_ID'] %>
  GOOGLE_CLIENT_SECRET:  <%= ENV['GOOGLE_CLIENT_SECRET'] %>

test:
  secret_key_base: your_test_secret_key

production:
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
  GOOGLE_CLIENT_ID:  <%= ENV['GOOGLE_CLIENT_ID'] %>
  GOOGLE_CLIENT_SECRET:  <%= ENV['GOOGLE_CLIENT_SECRET'] %>